services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - webroot:/webroot/browser
    command: >
      sh -lc "
        npm ci &&
        npx ng build --watch --poll 200  --configuration production --output-path=/webroot --delete-output-path=false
      "
    
  apache:
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - frontend
    volumes:
      - webroot:/var/www/html
      - ./backend:/var/www/html/backend
      - ./docker/backend/.env.local:/var/www/html/backend/.env.local:ro
      - ./docker/apache/.htaccess:/var/www/html/.htaccess:ro
    tmpfs:
      - /var/www/html/backend/var:uid=33,gid=33,mode=0775

  php_tools:
    image: composer:2
    working_dir: /app
    volumes:
      - ./backend:/app
    profiles: ["tools"]

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sp_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - "./locale/mysql:/var/lib/mysql"

  mail:
    image: axllent/mailpit:v1.28.0
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  webroot: