services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    working_dir: /var/www/backend
    environment:
      APP_ENV: dev
    volumes:
      - ./backend:/var/www/backend:delegated
      - ./docker/backend/.env.local:/var/www/backend/.env.local:ro
      - ./docker/backend/dev.ini:/usr/locale/etc/php/conf.d/dev.ini:ro
    tmpfs:
      - /var/www/backend/var/cache
    container_name: backend
    depends_on:
      - 'rabbitmq'

  worker:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    working_dir: /var/www/backend
    environment:
      APP_ENV: dev
    volumes:
      - ./backend:/var/www/backend:delegated
      - ./docker/backend/.env.local:/var/www/backend/.env.local:ro
      - ./docker/backend/dev.ini:/usr/locale/etc/php/conf.d/dev.ini:ro
    tmpfs:
      - /var/www/backend/var/cache
    container_name: worker
    command: 'php bin/console messenger:consume async -vv --time-limit=3600 --memory-limit=128M --sleep=1'
    restart: 'unless-stopped'
    depends_on:
      - 'rabbitmq'
      - 'backend'

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app:delegated

  nginx:
    image: nginx:1.27-alpine
    container_name: web
    depends_on:
      - backend
      - frontend
    ports:
      - "8081:80"
    volumes:
      - ./backend:/var/www/backend:ro
      - ./frontend/dist/frontend/browser:/usr/share/nginx/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sp_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - "./locale/mysql:/var/lib/mysql"

  mail:
    image: axllent/mailpit:v1.28.0
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  rabbitmq:
    image: rabbitmq:4.2.2-management
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: usermq
      RABBITMQ_DEFAULT_PASS: passwordmq
    volumes:
      - "./locale/rabbitmq:/var/lib/rabbitmq"
      
